### ISSUE TITLE
Suggestion - NUnit test `ILogger` implementation

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.testing#27]
**Is your feature request related to a problem? Please describe.**
Should we invest in an NUnit `ILogger` implementation? Just like we have one for the xUnit package?
Not sure if MSTest also has something speciifc?

**Describe the solution you'd like**
Provides a proxy to passthru the messages to the test output.
I'm not sure if there's also a specific logger for NUnit or we would have to use just the `Console.WriteLine`.

**Describe alternatives you've considered**
Maybe there's some other packages that already does this for us, not sure.

**Comment by tomkerkhove** [comment]
It can certainly be useful but maybe we should wait for the demand?

**Comment by stijnmoreels** [comment]
> It can certainly be useful but maybe we should wait for the demand?

Yes, of course. We can do that.

**Comment by stijnmoreels** [comment]
Closing issue for now.
